// ──────────────────────────────────────────────────────────────────────────
// « Tu préfères ? » — la grande banque de dilemmes du comptoir.
// Objectif : faire réfléchir, débattre et RIGOLER pendant 1 à 2 h. Beaucoup de
// thèmes (les astres, la réalité, l'absurde, la société, l'amour…), volontairement
// PAS centrés sur l'alcool. À jouer à plusieurs, on argumente, on se chambre.
// ──────────────────────────────────────────────────────────────────────────

export interface Dilemme {
  a: string;
  b: string;
  cat: string;
}

export interface CategorieTP {
  cle: string;
  nom: string;
  emoji: string;
}

export const CATEGORIES_TP: CategorieTP[] = [
  { cle: "astres", nom: "Astres & espace", emoji: "🪐" },
  { cle: "reel", nom: "Réalité & existence", emoji: "🌀" },
  { cle: "pouvoirs", nom: "Super-pouvoirs", emoji: "🦸" },
  { cle: "absurde", nom: "Absurde total", emoji: "🤪" },
  { cle: "societe", nom: "Société & quotidien", emoji: "🏙️" },
  { cle: "amour", nom: "Amour & amitié", emoji: "❤️" },
  { cle: "voyage", nom: "Voyage & aventure", emoji: "🌍" },
  { cle: "fete", nom: "Fêtes & comptoir", emoji: "🎉" },
  { cle: "moral", nom: "Dilemmes moraux", emoji: "⚖️" },
  { cle: "nostalgie", nom: "Nostalgie & culture", emoji: "📼" },
  { cle: "nature", nom: "Animaux & nature", emoji: "🐙" },
  { cle: "corps", nom: "Corps & superpouvoirs ratés", emoji: "🧠" },
];

export const DILEMMES: Dilemme[] = [
  // ── Astres & espace ──────────────────────────────────────────────────────
  { cat: "astres", a: "Être le premier humain à marcher sur Mars, mais ne jamais revenir sur Terre", b: "Rester sur Terre mais savoir exactement ce qu'il y a après la mort" },
  { cat: "astres", a: "Passer une nuit seul dans la Station spatiale internationale", b: "Passer une nuit seul au fond de la fosse des Mariannes" },
  { cat: "astres", a: "Découvrir une planète habitable et lui donner ton prénom", b: "Découvrir une forme de vie extraterrestre microscopique" },
  { cat: "astres", a: "Voir une éclipse totale tous les jours", b: "Voir une pluie d'étoiles filantes une fois par mois" },
  { cat: "astres", a: "Savoir si on est seuls dans l'univers", b: "Savoir comment l'univers va se terminer" },
  { cat: "astres", a: "Vivre sur une planète avec deux soleils (jamais de nuit)", b: "Vivre sur une planète avec trois lunes (nuits magnifiques)" },
  { cat: "astres", a: "Pouvoir respirer dans l'espace", b: "Pouvoir voyager à la vitesse de la lumière une seule fois" },
  { cat: "astres", a: "Assister au Big Bang en direct (sans risque)", b: "Assister à la naissance de la vie sur Terre" },
  { cat: "astres", a: "Avoir une étoile qui porte ton nom, visible à l'œil nu", b: "Avoir un cratère lunaire à ton nom, invisible d'ici" },
  { cat: "astres", a: "Comprendre enfin ce qu'est un trou noir en le voyant", b: "Comprendre enfin ce qu'il y avait avant le Big Bang" },
  { cat: "astres", a: "Recevoir un message d'une civilisation extraterrestre", b: "Envoyer un message qu'ils recevront dans 10 000 ans" },
  { cat: "astres", a: "Flotter en apesanteur pendant une semaine", b: "Marcher sur la Lune pendant une heure" },
  { cat: "astres", a: "Savoir ton avenir grâce aux astres, à coup sûr", b: "Pouvoir changer ton passé, une seule fois" },
  { cat: "astres", a: "Voir la Terre depuis l'espace une fois dans ta vie", b: "Voir les anneaux de Saturne de tes propres yeux, de près" },
  { cat: "astres", a: "Être immortel mais seul dans l'univers", b: "Vivre 80 ans entouré de tous ceux que tu aimes" },
  { cat: "astres", a: "Coloniser une nouvelle planète avec 100 humains au hasard", b: "Rester sur une Terre bondée mais avec tes proches" },

  // ── Réalité & existence ──────────────────────────────────────────────────
  { cat: "reel", a: "Apprendre qu'on vit dans une simulation", b: "Ne jamais le savoir et vivre tranquille" },
  { cat: "reel", a: "Pouvoir mettre la vie sur pause 1 h par jour", b: "Pouvoir la rembobiner de 10 minutes, une fois par jour" },
  { cat: "reel", a: "Connaître la date exacte de ta mort", b: "Connaître la cause exacte de ta mort" },
  { cat: "reel", a: "Revivre le même jour, parfait, à l'infini", b: "Vivre une vie normale, imprévisible et unique" },
  { cat: "reel", a: "Lire dans les pensées des autres", b: "Que personne ne puisse jamais te mentir" },
  { cat: "reel", a: "Oublier un souvenir douloureux pour toujours", b: "Le garder mais garder aussi la leçon apprise" },
  { cat: "reel", a: "Savoir ce que les gens pensent vraiment de toi", b: "Ne jamais le savoir et rester serein" },
  { cat: "reel", a: "Vivre 200 ans en bonne santé", b: "Vivre 80 ans mais te rappeler chaque instant parfaitement" },
  { cat: "reel", a: "Recommencer ta vie à 10 ans en gardant ta mémoire", b: "Continuer ta vie actuelle sans rien changer" },
  { cat: "reel", a: "Voir une version de toi qui a fait tous les autres choix", b: "Ne jamais douter de tes propres choix" },
  { cat: "reel", a: "Comprendre parfaitement toutes les langues du monde", b: "Parler avec les animaux" },
  { cat: "reel", a: "Que le libre arbitre existe vraiment", b: "Que tout soit écrit d'avance mais que tu te sentes libre" },
  { cat: "reel", a: "Rêver chaque nuit d'une vie entière alternative", b: "Ne jamais rêver mais dormir parfaitement" },
  { cat: "reel", a: "Savoir la vérité même si elle détruit tes illusions", b: "Vivre heureux dans une belle illusion" },
  { cat: "reel", a: "Pouvoir ressentir exactement ce que ressent l'autre", b: "Rester totalement maître de tes propres émotions" },
  { cat: "reel", a: "Que le temps ralentisse quand tu es heureux", b: "Que le temps accélère quand tu t'ennuies" },

  // ── Super-pouvoirs ───────────────────────────────────────────────────────
  { cat: "pouvoirs", a: "Voler", b: "Être invisible quand tu veux" },
  { cat: "pouvoirs", a: "Te téléporter n'importe où", b: "Arrêter le temps pour tout le monde sauf toi" },
  { cat: "pouvoirs", a: "Guérir n'importe quelle blessure d'un toucher", b: "Ne jamais tomber malade ni vieillir" },
  { cat: "pouvoirs", a: "Parler et comprendre toutes les langues", b: "Être une machine à retenir tout ce que tu lis" },
  { cat: "pouvoirs", a: "Contrôler le feu", b: "Contrôler l'eau" },
  { cat: "pouvoirs", a: "Devenir super fort", b: "Devenir super intelligent" },
  { cat: "pouvoirs", a: "Respirer sous l'eau", b: "Survivre dans le vide spatial" },
  { cat: "pouvoirs", a: "Copier n'importe quelle compétence en la regardant 1 min", b: "Rejouer n'importe quelle journée jusqu'à la réussir" },
  { cat: "pouvoirs", a: "Te dédoubler pour être à deux endroits", b: "Ne jamais avoir besoin de dormir" },
  { cat: "pouvoirs", a: "Transformer n'importe quoi en or (une fois par jour)", b: "Deviner à coup sûr le résultat d'un pari (une fois par jour)" },
  { cat: "pouvoirs", a: "Faire pousser n'importe quelle plante instantanément", b: "Parler aux animaux et qu'ils t'obéissent" },
  { cat: "pouvoirs", a: "Lire l'avenir mais sans jamais pouvoir le changer", b: "Effacer un mauvais souvenir des autres" },
  { cat: "pouvoirs", a: "Voler comme Superman mais lentement (30 km/h)", b: "Courir à 300 km/h mais au sol seulement" },
  { cat: "pouvoirs", a: "Être invincible mais ne jamais ressentir le plaisir", b: "Ressentir tout intensément mais rester fragile" },
  { cat: "pouvoirs", a: "Avoir un pouvoir énorme mais imprévisible", b: "Avoir un petit pouvoir mais totalement maîtrisé" },
  { cat: "pouvoirs", a: "Rendre les autres heureux d'un claquement de doigts", b: "Être toi-même heureux en permanence" },

  // ── Absurde total ────────────────────────────────────────────────────────
  { cat: "absurde", a: "Avoir des spaghettis à la place des cheveux (qui repoussent)", b: "Éternuer des confettis à chaque fois" },
  { cat: "absurde", a: "Parler uniquement en rimes toute ta vie", b: "Chanter tout ce que tu dis, comme une comédie musicale" },
  { cat: "absurde", a: "Avoir des mains de bébé", b: "Avoir des pieds de géant (pointure 58)" },
  { cat: "absurde", a: "Que tout ce que tu touches devienne collant", b: "Que tout ce que tu touches fasse un bruit de canard" },
  { cat: "absurde", a: "Être poursuivi par un poulet géant une fois par semaine", b: "Devoir combattre 100 poulets normaux une fois par an" },
  { cat: "absurde", a: "Avoir un rire de sorcière incontrôlable", b: "Pleurer à chaque fois que tu ris" },
  { cat: "absurde", a: "T'habiller en pirate tous les jours pour toujours", b: "Parler comme un chevalier du Moyen Âge" },
  { cat: "absurde", a: "Avoir une queue de chat qui trahit tes émotions", b: "Avoir des oreilles qui bougent quand tu mens" },
  { cat: "absurde", a: "Sentir en permanence la barbe à papa", b: "Entendre une musique de cirque quand tu marches" },
  { cat: "absurde", a: "Avoir toujours un caillou dans la chaussure", b: "Avoir toujours une étiquette qui gratte dans le cou" },
  { cat: "absurde", a: "Devoir crier « BANANE ! » avant chaque phrase", b: "Devoir faire un tour sur toi-même avant de t'asseoir" },
  { cat: "absurde", a: "Avoir la peau qui change de couleur selon ton humeur", b: "Avoir les cheveux qui poussent de 10 cm quand tu mens" },
  { cat: "absurde", a: "Vivre dans un monde en noir et blanc mais heureux", b: "Vivre en couleurs mais où tout a un goût de carton" },
  { cat: "absurde", a: "Te transformer en statue quand quelqu'un te regarde", b: "Devenir invisible mais seulement quand personne ne regarde" },
  { cat: "absurde", a: "Avoir un mini-toi sur l'épaule qui commente ta vie", b: "Avoir un narrateur de documentaire animalier qui te suit" },
  { cat: "absurde", a: "Toujours porter un déguisement de dinosaure", b: "Toujours te déplacer en trottinette, même à l'intérieur" },

  // ── Société & quotidien ──────────────────────────────────────────────────
  { cat: "societe", a: "Ne plus jamais avoir à travailler mais gagner le minimum", b: "Adorer ton travail mais bosser 6 jours sur 7" },
  { cat: "societe", a: "Gagner au loto mais que tout le monde le sache", b: "Gagner deux fois moins mais que personne ne le sache" },
  { cat: "societe", a: "Ne plus jamais faire la queue nulle part", b: "Ne plus jamais être coincé dans les embouteillages" },
  { cat: "societe", a: "Avoir la maison de tes rêves au milieu de nulle part", b: "Avoir un petit appart en plein cœur de ta ville préférée" },
  { cat: "societe", a: "Un métier passionnant mais mal payé", b: "Un métier ennuyeux mais très bien payé" },
  { cat: "societe", a: "Ne plus jamais payer d'impôts", b: "Ne plus jamais payer de loyer/crédit" },
  { cat: "societe", a: "Être célèbre mais critiqué", b: "Être inconnu mais respecté de tes proches" },
  { cat: "societe", a: "Télétravailler à vie", b: "Aller au bureau mais finir à 15 h tous les jours" },
  { cat: "societe", a: "Ne plus jamais avoir mal aux dents", b: "Ne plus jamais avoir mal au dos" },
  { cat: "societe", a: "Vivre à la campagne au calme", b: "Vivre en ville avec tout à portée" },
  { cat: "societe", a: "Retrouver 2 h de temps libre par jour", b: "Retrouver 1 000 € par mois" },
  { cat: "societe", a: "Ne plus jamais être en retard", b: "Ne plus jamais oublier un nom ni un anniversaire" },
  { cat: "societe", a: "Avoir internet illimité et gratuit à vie", b: "Avoir les transports gratuits à vie" },
  { cat: "societe", a: "Un patron génial dans un job moyen", b: "Un patron horrible dans le job de tes rêves" },
  { cat: "societe", a: "Devoir déménager tous les ans dans une nouvelle ville", b: "Ne plus jamais pouvoir quitter ta ville actuelle" },
  { cat: "societe", a: "Ne plus jamais avoir de spam ni de pub", b: "Ne plus jamais avoir de bug informatique" },

  // ── Amour & amitié ───────────────────────────────────────────────────────
  { cat: "amour", a: "Trouver l'amour parfait mais à l'autre bout du monde", b: "Un amour très bien mais qui habite juste à côté" },
  { cat: "amour", a: "Savoir que ton crush pense à toi en ce moment", b: "Ne jamais douter de tes amitiés" },
  { cat: "amour", a: "Avoir 3 amis fidèles pour la vie", b: "Avoir 100 connaissances sympas mais superficielles" },
  { cat: "amour", a: "Que ton/ta partenaire lise dans tes pensées", b: "Lire dans les siennes" },
  { cat: "amour", a: "Un grand amour de 5 ans intenses", b: "Une relation tranquille et solide de 50 ans" },
  { cat: "amour", a: "Te réconcilier avec quelqu'un que tu as perdu de vue", b: "Rencontrer quelqu'un de totalement nouveau" },
  { cat: "amour", a: "Être toujours celui qui aime le plus", b: "Être toujours celui qu'on aime le plus" },
  { cat: "amour", a: "Dire ce que tu ressens vraiment sans filtre pendant un jour", b: "Entendre ce que les autres ressentent vraiment pour toi" },
  { cat: "amour", a: "Un premier rendez-vous parfait mais imprévisible", b: "Une amitié qui se transforme lentement en amour" },
  { cat: "amour", a: "Avoir un ami qui te dit toujours la vérité, même dure", b: "Un ami qui te soutient toujours, même à tort" },
  { cat: "amour", a: "Retrouver ton amour de jeunesse", b: "Rencontrer ton âme sœur demain" },
  { cat: "amour", a: "Vivre une belle histoire d'amour dont tu perdras la mémoire", b: "T'en souvenir toute ta vie mais qu'elle finisse mal" },
  { cat: "amour", a: "Que tes amis choisissent ton/ta partenaire", b: "Choisir seul mais sans leur avis" },
  { cat: "amour", a: "Un mariage de rêve à 100 invités", b: "Une demande surprise en tête-à-tête inoubliable" },
  { cat: "amour", a: "Pardonner facilement mais te faire souvent avoir", b: "Pardonner difficilement mais te protéger" },
  { cat: "amour", a: "Être aimé pour ce que tu montres", b: "Être aimé pour ce que tu caches" },

  // ── Voyage & aventure ────────────────────────────────────────────────────
  { cat: "voyage", a: "Faire le tour du monde une fois, sac au dos", b: "Retourner 20 fois dans le pays que tu adores" },
  { cat: "voyage", a: "Voyager dans le futur de 100 ans", b: "Voyager dans le passé de 100 ans" },
  { cat: "voyage", a: "Visiter tous les pays mais 2 jours chacun", b: "Vivre un an dans un seul pays étranger" },
  { cat: "voyage", a: "Une croisière de luxe tout confort", b: "Une expédition en pleine nature, rustique mais épique" },
  { cat: "voyage", a: "Voir une aurore boréale", b: "Plonger dans la Grande Barrière de corail" },
  { cat: "voyage", a: "Voyager gratuitement à vie mais toujours seul", b: "Payer tes voyages mais toujours accompagné" },
  { cat: "voyage", a: "Passer une nuit dans une pyramide d'Égypte", b: "Passer une nuit au sommet du mont Fuji" },
  { cat: "voyage", a: "Parler la langue de chaque pays visité", b: "Avoir un guide local dans chaque pays" },
  { cat: "voyage", a: "Un road trip improvisé sans plan", b: "Un voyage parfaitement organisé minute par minute" },
  { cat: "voyage", a: "Explorer une jungle inconnue", b: "Explorer une grotte sous-marine" },
  { cat: "voyage", a: "Voyager dans le temps mais en simple spectateur", b: "Voyager dans l'espace mais en simple touriste" },
  { cat: "voyage", a: "Randonner seul pendant un mois", b: "Faire la fête dans une ville différente chaque soir" },
  { cat: "voyage", a: "Découvrir une cité perdue avant tout le monde", b: "Retrouver un trésor et le partager" },
  { cat: "voyage", a: "Une vie de nomade sans maison fixe", b: "Une maison de rêve mais rester au même endroit" },

  // ── Fêtes & comptoir ─────────────────────────────────────────────────────
  { cat: "fete", a: "Une soirée mémorable dont tu ne te souviens plus", b: "Une soirée moyenne mais gravée dans ta mémoire" },
  { cat: "fete", a: "Être toujours le boute-en-train de la soirée", b: "Être celui qui prend soin de tout le monde" },
  { cat: "fete", a: "Organiser la fête parfaite mais chez toi (rangement inclus)", b: "Aller à la fête parfaite ailleurs, sans rien gérer" },
  { cat: "fete", a: "Un karaoké endiablé toute la nuit", b: "Un blind test acharné en équipe" },
  { cat: "fete", a: "Danser toute la nuit sans te fatiguer", b: "Tenir une conversation passionnante jusqu'au petit matin" },
  { cat: "fete", a: "Gagner à tous les jeux de société", b: "Perdre mais toujours faire rire la table" },
  { cat: "fete", a: "Une grande fête avec 200 inconnus sympas", b: "Une petite soirée avec tes 6 meilleurs potes" },
  { cat: "fete", a: "Être le meilleur au baby-foot", b: "Être imbattable aux fléchettes" },
  { cat: "fete", a: "Toujours avoir la meilleure anecdote à raconter", b: "Toujours savoir écouter et poser LA bonne question" },
  { cat: "fete", a: "Faire un discours qui fait pleurer de rire", b: "Faire un discours qui fait pleurer d'émotion" },
  { cat: "fete", a: "Un festival de musique 3 jours sous la pluie", b: "Un concert unique de ton artiste préféré, parfait" },
  { cat: "fete", a: "Rentrer à pied 1 h en refaisant le monde avec un pote", b: "Rentrer en 10 min mais seul et en silence" },
  { cat: "fete", a: "Être invité à toutes les fêtes de la ville", b: "N'être invité qu'aux fêtes vraiment réussies" },
  { cat: "fete", a: "La tournée offerte par le patron", b: "Le dernier verre en terrasse au coucher du soleil" },

  // ── Dilemmes moraux ──────────────────────────────────────────────────────
  { cat: "moral", a: "Sauver 5 inconnus", b: "Sauver 1 proche" },
  { cat: "moral", a: "Dire une vérité qui blesse", b: "Un mensonge qui protège" },
  { cat: "moral", a: "Trouver un portefeuille plein et le rendre", b: "Le garder si personne ne le sait jamais" },
  { cat: "moral", a: "Rendre le monde plus juste mais plus ennuyeux", b: "Le garder injuste mais plein de surprises" },
  { cat: "moral", a: "Pouvoir gracier un condamné, à toi seul de décider", b: "Ne jamais avoir à décider de la vie des autres" },
  { cat: "moral", a: "Être toujours honnête même quand ça te dessert", b: "Arranger la vérité pour t'en sortir" },
  { cat: "moral", a: "Dénoncer un ami qui a triché", b: "Le couvrir et porter le secret" },
  { cat: "moral", a: "Aider anonymement sans jamais de reconnaissance", b: "Aider publiquement et être remercié" },
  { cat: "moral", a: "Effacer la pauvreté mais que personne ne s'en souvienne", b: "Réduire la pauvreté de moitié et rester dans l'Histoire" },
  { cat: "moral", a: "Sacrifier un an de ta vie pour sauver un inconnu", b: "Garder ton année mais vivre avec ce choix" },
  { cat: "moral", a: "Pouvoir punir tous les tricheurs mais parfois te tromper", b: "Ne jamais te tromper mais laisser filer les tricheurs" },
  { cat: "moral", a: "Redistribuer ta fortune si tu en avais une", b: "La garder pour assurer l'avenir de tes proches" },
  { cat: "moral", a: "Connaître tous les secrets de tes proches", b: "Qu'ils connaissent tous les tiens" },
  { cat: "moral", a: "Sauver l'art et la culture mais perdre la technologie", b: "Garder la technologie mais perdre l'art" },

  // ── Nostalgie & culture ──────────────────────────────────────────────────
  { cat: "nostalgie", a: "Revivre ton meilleur souvenir d'enfance une fois", b: "Créer un nouveau souvenir aussi fort demain" },
  { cat: "nostalgie", a: "N'écouter qu'un seul album pour le reste de ta vie", b: "Ne jamais réécouter tes chansons préférées mais découvrir plein de neuf" },
  { cat: "nostalgie", a: "Vivre dans les années 80", b: "Vivre dans les années 2000" },
  { cat: "nostalgie", a: "Ne regarder que des films avant l'an 2000", b: "Ne regarder que des films sortis après" },
  { cat: "nostalgie", a: "Rejouer à tes jeux d'enfance à l'infini", b: "Découvrir chaque année LE jeu du moment" },
  { cat: "nostalgie", a: "Revoir ton dessin animé préféré pour la 1re fois", b: "Lire ton livre préféré pour la 1re fois" },
  { cat: "nostalgie", a: "Retrouver un objet perdu de ton enfance", b: "Retrouver un ami d'enfance perdu de vue" },
  { cat: "nostalgie", a: "Connaître par cœur tous les films", b: "Connaître par cœur toutes les chansons" },
  { cat: "nostalgie", a: "Que ta série préférée n'ait jamais de fin", b: "Qu'elle ait une fin parfaite mais définitive" },
  { cat: "nostalgie", a: "Garder tes goûts musicaux figés à jamais", b: "Aimer une nouvelle musique chaque semaine" },
  { cat: "nostalgie", a: "Rencontrer ton idole d'enfance", b: "Rencontrer ton idole actuelle" },
  { cat: "nostalgie", a: "Un monde sans smartphone mais avec du courrier", b: "Le monde connecté actuel avec ses notifications" },
  { cat: "nostalgie", a: "Retomber en enfance un week-end", b: "Sauter directement à ta retraite un week-end" },
  { cat: "nostalgie", a: "Garder une photo de chaque instant de ta vie", b: "Garder une odeur qui te ramène à chaque souvenir" },

  // ── Animaux & nature ─────────────────────────────────────────────────────
  { cat: "nature", a: "Avoir un dragon miniature comme animal de compagnie", b: "Avoir une licorne qui tient dans le jardin" },
  { cat: "nature", a: "Comprendre le langage des chats", b: "Comprendre le langage des chiens" },
  { cat: "nature", a: "Te transformer en aigle une heure par jour", b: "Te transformer en dauphin une heure par jour" },
  { cat: "nature", a: "Avoir un ours géant gentil comme garde du corps", b: "Avoir une meute de loups fidèles" },
  { cat: "nature", a: "Vivre dans une forêt enchantée", b: "Vivre sur une île déserte paradisiaque" },
  { cat: "nature", a: "Que les plantes te parlent", b: "Que les animaux te suivent partout" },
  { cat: "nature", a: "Nager avec les baleines", b: "Voler avec les oiseaux migrateurs" },
  { cat: "nature", a: "Ne plus jamais avoir froid", b: "Ne plus jamais avoir chaud" },
  { cat: "nature", a: "Un jardin qui pousse tout seul, magnifique", b: "Une maison qui se nettoie toute seule" },
  { cat: "nature", a: "Passer une saison à observer les animaux sauvages", b: "Passer une saison à explorer les fonds marins" },
  { cat: "nature", a: "Avoir des ailes mais fragiles", b: "Avoir des branchies mais toujours mouillé" },
  { cat: "nature", a: "Vivre 100 ans comme une tortue tranquille", b: "Vivre 2 ans intenses comme un guépard" },
  { cat: "nature", a: "Faire repousser une forêt d'un claquement de doigts", b: "Nettoyer un océan entier d'un claquement de doigts" },
  { cat: "nature", a: "Ne manger que des fruits pour toujours", b: "Ne manger que du salé pour toujours" },

  // ── Corps & superpouvoirs ratés ──────────────────────────────────────────
  { cat: "corps", a: "Pouvoir manger tout ce que tu veux sans grossir", b: "Ne jamais avoir besoin de dormir" },
  { cat: "corps", a: "Ne plus jamais te fatiguer", b: "Ne plus jamais être malade" },
  { cat: "corps", a: "Une mémoire parfaite mais un sommeil agité", b: "Une mémoire moyenne mais un sommeil de bébé" },
  { cat: "corps", a: "Courir un marathon sans t'entraîner", b: "Soulever 200 kg sans effort" },
  { cat: "corps", a: "Ne plus jamais avoir la gueule de bois", b: "Ne plus jamais avoir mal aux jambes après le sport" },
  { cat: "corps", a: "Guérir en dormant une nuit", b: "Ne jamais ressentir la douleur" },
  { cat: "corps", a: "Avoir une voix magnifique", b: "Savoir danser divinement" },
  { cat: "corps", a: "Être le plus rapide du monde mais maladroit", b: "Le plus habile du monde mais lent" },
  { cat: "corps", a: "Pouvoir digérer n'importe quoi", b: "Ne jamais avoir soif ni faim" },
  { cat: "corps", a: "Un cerveau surpuissant mais un corps fragile", b: "Un corps d'athlète mais une mémoire de poisson rouge" },
  { cat: "corps", a: "Avoir toujours l'air 10 ans plus jeune", b: "Avoir toujours l'énergie de tes 20 ans" },
  { cat: "corps", a: "Sentir les émotions par le toucher", b: "Voir les mensonges à l'œil nu" },
];

// Gages pour les dégonflés qui refusent de choisir (mode challenge). Bon enfant,
// jamais lié à l'alcool : on rigole, on ne pousse personne à boire.
export const GAGES: string[] = [
  "Imite l'accent d'une région au hasard jusqu'à ton prochain tour.",
  "Fais un compliment sincère à chaque personne de la table.",
  "Parle en chantant tout ce que tu dis pendant 2 minutes.",
  "Raconte ta plus grosse honte de collège.",
  "Fais deviner un film uniquement en mimant, 30 secondes.",
  "Prends l'accent d'un présentateur télé jusqu'au prochain dilemme.",
  "Danse 15 secondes sans musique, à fond.",
  "Laisse ton voisin de droite écrire ton prochain statut imaginaire.",
  "Fais ton meilleur bruitage d'animal, la table doit deviner lequel.",
  "Refais la dernière pub que tu as en tête, avec conviction.",
  "Parle uniquement à la 3e personne pendant 1 minute.",
  "Fais un discours de remerciement comme si tu gagnais un oscar.",
  "Imite quelqu'un de la table, les autres doivent deviner qui.",
  "Invente un proverbe et défends-le sérieusement.",
  "Fais 10 pompes ou 10 squats (au choix), tout de suite.",
  "Raconte une anecdote gênante… mais fausse, et fais-la passer pour vraie.",
  "Chante le refrain de la première chanson qui te vient.",
  "Fais le tour de la pièce en marchant comme un mannequin.",
  "Complimente la déco de la pièce comme un critique d'art snob.",
  "Réponds à la prochaine question de quelqu'un uniquement par des questions.",
  "Prends la pose la plus héroïque possible et tiens-la 20 secondes.",
  "Fais une déclaration d'amour enflammée… à un objet de la pièce.",
  "Raconte ton pire rendez-vous (ou invente-le).",
  "Imite un robot pour tout ce que tu diras pendant 1 minute.",
  "Fais deviner ton métier de rêve en le mimant.",
  "Fais le commentateur sportif de ce que fait ton voisin.",
  "Termine chaque phrase par « …et c'est comme ça » pendant 2 minutes.",
  "Fais un câlin collectif de 5 secondes à toute la table.",
  "Invente un cri de guerre pour la soirée, tout le monde le répète.",
  "Fais le service : ressers à boire (eau, soft, ce que tu veux) à tout le monde.",
];
